#ifndef THREADMEDIATOR_GLOBAL_H
#define THREADMEDIATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THREADMEDIATOR_LIBRARY)
#  define THREADMEDIATOR_EXPORT Q_DECL_EXPORT
#else
#  define THREADMEDIATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // THREADMEDIATOR_GLOBAL_H
